{% set name = "RedLionfish" %}
{% set version = "0.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ..

build:
  #Definining no architecture will mean that ocl-icd-system will never get installed in linux
  #Need to manually create package in the linux
  #noarch: python
  number: 0
  
  #Script to use if don't want to use the bld.bat or build.sh step
  #script: python setup.py install

requirements:
  host: #Specific for to the target platform
    - python
    - pip

  run: #packages required to run the package, to install automatically when this package is installed using conda install
    - python
    - numpy
    - scipy
    - pyopencl
    - reikna

    # for opencl to work correctly in linux, the following package helps. Preprocessing selector is used.
    - ocl-icd-system # [linux]

test:
  imports:
    - RedLionfishDeconv

about:
  home: https://github.com/rosalindfranklininstitute/RedLionfish
  license: Apache License, Version 2.0
  license_file: LICENSE
  summary: Richardson-Lucy deconvolution of 3D data